// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rezervist.Data;

#nullable disable

namespace Rezervist.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106162430_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rezervist.Models.Misafir", b =>
                {
                    b.Property<int>("MisafirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MisafirID"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCKimlik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MisafirID");

                    b.ToTable("Misafirler");
                });

            modelBuilder.Entity("Rezervist.Models.Oda", b =>
                {
                    b.Property<int>("OdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OdaID"));

                    b.Property<bool>("DoluMu")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("OdaNumarasi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OdaID");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("Rezervist.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RezervasyonID"));

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MisafirID")
                        .HasColumnType("integer");

                    b.Property<int>("OdaID")
                        .HasColumnType("integer");

                    b.HasKey("RezervasyonID");

                    b.HasIndex("MisafirID");

                    b.HasIndex("OdaID");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("Rezervist.Models.Rezervasyon", b =>
                {
                    b.HasOne("Rezervist.Models.Misafir", "Misafir")
                        .WithMany()
                        .HasForeignKey("MisafirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rezervist.Models.Oda", "Oda")
                        .WithMany()
                        .HasForeignKey("OdaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Misafir");

                    b.Navigation("Oda");
                });
#pragma warning restore 612, 618
        }
    }
}
