// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rezervist.Data;

#nullable disable

namespace Rezervist.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rezervist.Models.Harcama", b =>
                {
                    b.Property<int>("HarcamaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HarcamaID"));

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RezervasyonID")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("text");

                    b.HasKey("HarcamaID");

                    b.HasIndex("RezervasyonID");

                    b.ToTable("Harcamalar");
                });

            modelBuilder.Entity("Rezervist.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KullaniciID"));

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text");

                    b.Property<string>("Sifre")
                        .HasColumnType("text");

                    b.HasKey("KullaniciID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Rezervist.Models.Misafir", b =>
                {
                    b.Property<int>("MisafirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MisafirID"));

                    b.Property<string>("AdSoyad")
                        .HasColumnType("text");

                    b.Property<bool>("KaraListedeMi")
                        .HasColumnType("boolean");

                    b.Property<string>("OzelNotlar")
                        .HasColumnType("text");

                    b.Property<string>("TCKimlik")
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("MisafirID");

                    b.ToTable("Misafirler");
                });

            modelBuilder.Entity("Rezervist.Models.Oda", b =>
                {
                    b.Property<int>("OdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OdaID"));

                    b.Property<bool>("DoluMu")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Fiyat")
                        .HasColumnType("numeric");

                    b.Property<string>("OdaNumarasi")
                        .HasColumnType("text");

                    b.Property<string>("OdaTipi")
                        .HasColumnType("text");

                    b.Property<string>("ResimUrl")
                        .HasColumnType("text");

                    b.Property<bool>("TemizMi")
                        .HasColumnType("boolean");

                    b.HasKey("OdaID");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("Rezervist.Models.Rezervasyon", b =>
                {
                    b.Property<int>("RezervasyonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RezervasyonID"));

                    b.Property<DateTime>("CikisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GirisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MisafirID")
                        .HasColumnType("integer");

                    b.Property<int>("OdaID")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeTuru")
                        .HasColumnType("text");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("numeric");

                    b.HasKey("RezervasyonID");

                    b.HasIndex("MisafirID");

                    b.HasIndex("OdaID");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("Rezervist.Models.Harcama", b =>
                {
                    b.HasOne("Rezervist.Models.Rezervasyon", "Rezervasyon")
                        .WithMany()
                        .HasForeignKey("RezervasyonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rezervasyon");
                });

            modelBuilder.Entity("Rezervist.Models.Rezervasyon", b =>
                {
                    b.HasOne("Rezervist.Models.Misafir", "Misafir")
                        .WithMany()
                        .HasForeignKey("MisafirID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rezervist.Models.Oda", "Oda")
                        .WithMany()
                        .HasForeignKey("OdaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Misafir");

                    b.Navigation("Oda");
                });
#pragma warning restore 612, 618
        }
    }
}
